services:
  # Service backend
  - type: web
    name: musical-duration-backend
    env: python
    buildCommand: cd backend && pip install -r requirements.txt
    startCommand: cd backend && gunicorn app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHONUNBUFFERED
        value: true
    autoDeploy: true

  # Service frontend
  - type: web
    name: musical-duration-frontend
    env: static
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: ./frontend/build
    routes:
      - type: rewrite
        source: /api/*
        destination: https://musical-duration-backend.onrender.com/api/:splat
    envVars:
      - key: REACT_APP_API_URL
        value: https://musical-duration-backend.onrender.com
    autoDeploy: true
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache 